// get profile
export const GET_PROFILE_DATA_REQUEST = "GET_PROFILE_DATA_REQUEST";
export const GET_PROFILE_DATA_SUCCESS = "GET_PROFILE_DATA_SUCCESS";
export const GET_PROFILE_DATA_ERROR = "GET_PROFILE_DATA_ERROR";

// create profile
export const ADD_PROFILE_DATA_REQUEST = "ADD_PROFILE_DATA_REQUEST";
export const ADD_PROFILE_DATA_SUCCESS = "ADD_PROFILE_DATA_SUCCESS";
export const ADD_PROFILE_DATA_ERROR = "ADD_PROFILE_DATA_ERROR";

// update profile
export const UPDATE_PROFILE_DATA_REQUEST = "UPDATE_PROFILE_DATA_REQUEST";
export const UPDATE_PROFILE_DATA_SUCCESS = "UPDATE_PROFILE_DATA_SUCCESS";
export const UPDATE_PROFILE_DATA_ERROR = "UPDATE_PROFILE_DATA_ERROR";
