// State Actions
export const GET_STATE_DATA_REQUEST = "GET_STATE_DATA_REQUEST";
export const GET_STATE_DATA_SUCCESS = "GET_STATE_DATA_SUCCESS";
export const GET_STATE_DATA_ERROR = "GET_STATE_DATA_ERROR";

export const ADD_STATE_DATA_REQUEST = "ADD_STATE_DATA_REQUEST";
export const ADD_STATE_DATA_SUCCESS = "ADD_STATE_DATA_SUCCESS";
export const ADD_STATE_DATA_ERROR = "ADD_STATE_DATA_ERROR";

// District Actions
export const GET_DISTRICT_DATA_REQUEST = "GET_DISTRICT_DATA_REQUEST";
export const GET_DISTRICT_DATA_SUCCESS = "GET_DISTRICT_DATA_SUCCESS";
export const GET_DISTRICT_DATA_ERROR = "GET_DISTRICT_DATA_ERROR";

export const ADD_DISTRICT_DATA_REQUEST = "ADD_DISTRICT_DATA_REQUEST";
export const ADD_DISTRICT_DATA_SUCCESS = "ADD_DISTRICT_DATA_SUCCESS";
export const ADD_DISTRICT_DATA_ERROR = "ADD_DISTRICT_DATA_ERROR";

// Zone Actions
export const GET_ZONE_DATA_REQUEST = "GET_ZONE_DATA_REQUEST";
export const GET_ZONE_DATA_SUCCESS = "GET_ZONE_DATA_SUCCESS";
export const GET_ZONE_DATA_ERROR = "GET_ZONE_DATA_ERROR";

export const ADD_ZONE_DATA_REQUEST = "ADD_ZONE_DATA_REQUEST";
export const ADD_ZONE_DATA_SUCCESS = "ADD_ZONE_DATA_SUCCESS";
export const ADD_ZONE_DATA_ERROR = "ADD_ZONE_DATA_ERROR";
