// get coordinator dashboard list
export const GET_COORDINAOR_DATA_REQUEST = "GET_COORDINAOR_DATA_REQUEST";
export const GET_COORDINAOR_DATA_SUCCESS = "GET_COORDINAOR_DATA_SUCCESS";
export const GET_COORDINAOR_DATA_ERROR = "GET_COORDINAOR_DATA_ERROR";



