// get field-executive
export const GET_FIELDEXECUTIVE_DATA_REQUEST =
  "GET_FIELDEXECUTIVE_DATA_REQUEST";
export const GET_FIELDEXECUTIVE_DATA_SUCCESS =
  "GET_FIELDEXECUTIVE_DATA_SUCCESS";
export const GET_FIELDEXECUTIVE_DATA_ERROR = "GET_FIELDEXECUTIVE_DATA_ERROR";

// create field-executive
export const ADD_FIELDEXECUTIVE_DATA_REQUEST =
  "ADD_FIELDEXECUTIVE_DATA_REQUEST";
export const ADD_FIELDEXECUTIVE_DATA_SUCCESS =
  "ADD_FIELDEXECUTIVE_DATA_SUCCESS";
export const ADD_FIELDEXECUTIVE_DATA_ERROR = "ADD_FIELDEXECUTIVE_DATA_ERROR";

// create field-executive
export const UPDATE_FIELDEXECUTIVE_DATA_REQUEST =
  "UPDATE_FIELDEXECUTIVE_DATA_REQUEST";
export const UPDATE_FIELDEXECUTIVE_DATA_SUCCESS =
  "UPDATE_FIELDEXECUTIVE_DATA_SUCCESS";
export const UPDATE_FIELDEXECUTIVE_DATA_ERROR =
  "UPDATE_FIELDEXECUTIVE_DATA_ERROR";
