export const GET_BANK_DATA_REQUEST = 'GET_BANK_DATA_REQUEST'
export const GET_BANK_DATA_SUCCESS = 'GET_BANK_DATA_SUCCESS'
export const GET_BANK_DATA_ERROR = 'GET_BANK_DATA_ERROR'

export const ADD_BANK_DATA_REQUEST = 'ADD_BANK_DATA_REQUEST'
export const ADD_BANK_DATA_SUCCESS = 'ADD_BANK_DATA_SUCCESS'
export const ADD_BANK_DATA_ERROR = 'ADD_BANK_DATA_ERROR'
