// get supervisor dashboard list
export const GET_SUPERVISOR_DATA_REQUEST = "GET_SUPERVISOR_DATA_REQUEST";
export const GET_SUPERVISOR_DATA_SUCCESS = "GET_SUPERVISOR_DATA_SUCCESS";
export const GET_SUPERVISOR_DATA_ERROR = "GET_SUPERVISOR_DATA_ERROR";



