// get case
export const GET_CASE_DATA_REQUEST = "GET_CASE_DATA_REQUEST";
export const GET_CASE_DATA_SUCCESS = "GET_CASE_DATA_SUCCESS";
export const GET_CASE_DATA_ERROR = "GET_CASE_DATA_ERROR";

// create case
export const ADD_CASE_DATA_REQUEST = "ADD_CASE_DATA_REQUEST";
export const ADD_CASE_DATA_SUCCESS = "ADD_CASE_DATA_SUCCESS";
export const ADD_CASE_DATA_ERROR = "ADD_CASE_DATA_ERROR";

// create case
export const UPDATE_CASE_DATA_REQUEST = "UPDATE_CASE_DATA_REQUEST";
export const UPDATE_CASE_DATA_SUCCESS = "UPDATE_CASE_DATA_SUCCESS";
export const UPDATE_CASE_DATA_ERROR = "UPDATE_CASE_DATA_ERROR";
