// Get all assign cases of Auditor
export const ALL_CASE_DATA_AUDITOR_REQUEST = "ALL_CASE_DATA_AUDITOR_REQUEST";
export const ALL_CASE_DATA_AUDITOR_SUCCESS = "ALL_CASE_DATA_AUDITOR_SUCCESS";
export const ALL_CASE_DATA_AUDITOR_ERROR = "ALL_CASE_DATA_AUDITOR_ERROR";


