// Get all assign cases of Auditor
export const ALL_CASE_DATA_AUDITOR_REQUEST = "ALL_CASE_DATA_AUDITOR_REQUEST";
export const ALL_CASE_DATA_AUDITOR_SUCCESS = "ALL_CASE_DATA_AUDITOR_SUCCESS";
export const ALL_CASE_DATA_AUDITOR_ERROR = "ALL_CASE_DATA_AUDITOR_ERROR";


// Get all case data of specific id by Auditor
export const CASE_DATA_ID_AUDITOR_REQUEST = "CASE_DATA_ID_AUDITOR_REQUEST";
export const CASE_DATA_ID_AUDITOR_SUCCESS = "CASE_DATA_ID_AUDITOR_SUCCESS";
export const CASE_DATA_ID_AUDITOR_ERROR = "CASE_DATA_ID_AUDITOR_ERROR";

// Get all case data of specific id by Auditor
export const APPROVE_DATA_BY_AUDITOR_REQUEST = "APPROVE_DATA_BY_AUDITOR_REQUEST";
export const APPROVE_DATA_BY_AUDITOR_SUCCESS = "APPROVE_DATA_BY_AUDITOR_SUCCESS";
export const APPROVE_DATA_BY_AUDITOR_ERROR = "APPROVE_DATA_BY_AUDITOR_ERROR";


