// get case
export const GET_SUPERVISOR_DATA_REQUEST = "GET_SUPERVISOR_DATA_REQUEST";
export const GET_SUPERVISOR_DATA_SUCCESS = "GET_SUPERVISOR_DATA_SUCCESS";
export const GET_SUPERVISOR_DATA_ERROR = "GET_SUPERVISOR_DATA_ERROR";

// get case by supervisor of specified id
export const GET_CASE_DATA_BY_SUPERVISOR_REQUEST = "GET_CASE_DATA_BY_SUPERVISOR_REQUEST";
export const GET_CASE_DATA_BY_SUPERVISOR_SUCCESS = "GET_CASE_DATA_BY_SUPERVISOR_SUCCESS";
export const GET_CASE_DATA_BY_SUPERVISOR_ERROR = "GET_CASE_DATA_BY_SUPERVISOR_ERROR";


// get case by supervisor of specified id
export const UPDATE_DATA_BY_SUPERVISOR_REQUEST = "UPDATE_DATA_BY_SUPERVISOR_REQUEST";
export const UPDATE_DATA_BY_SUPERVISOR_SUCCESS = "UPDATE_DATA_BY_SUPERVISOR_SUCCESS";
export const UPDATE_DATA_BY_SUPERVISOR_ERROR = "UPDATE_DATA_BY_SUPERVISOR_ERROR";


