// get case
export const GET_SUPERVISOR_DATA_REQUEST = "GET_SUPERVISOR_DATA_REQUEST";
export const GET_SUPERVISOR_DATA_SUCCESS = "GET_SUPERVISOR_DATA_SUCCESS";
export const GET_SUPERVISOR_DATA_ERROR = "GET_SUPERVISOR_DATA_ERROR";

export const GET_CASE_DATA_BY_SUPERVISOR_REQUEST = "GET_CASE_DATA_BY_SUPERVISOR_REQUEST";
export const GET_CASE_DATA_BY_SUPERVISOR_SUCCESS = "GET_CASE_DATA_BY_SUPERVISOR_SUCCESS";
export const GET_CASE_DATA_BY_SUPERVISOR_ERROR = "GET_CASE_DATA_BY_SUPERVISOR_ERROR";
