export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

// otp while login
export const USER_LOGIN_OTP_REQUEST = "USER_LOGIN_OTP_REQUEST";
export const USER_LOGIN_OTP_SUCCESS = "USER_LOGIN_OTP_SUCCESS";
export const USER_LOGIN_OTP_ERROR = "USER_LOGIN_OTP_ERROR";
