export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR";

// otp while login
export const USER_LOGIN_OTP_REQUEST = "USER_LOGIN_OTP_REQUEST";
export const USER_LOGIN_OTP_SUCCESS = "USER_LOGIN_OTP_SUCCESS";
export const USER_LOGIN_OTP_ERROR = "USER_LOGIN_OTP_ERROR";


// otp for forget password

export const USER_FORGET_PASSWORD_REQUEST="USER_FORGET_PASSWORD_REQUEST";
export const USER_FORGET_PASSWORD_SUCCESS="USER_FORGET_PASSWORD_SUCCESS";
export const USER_FORGET_PASSWORD_ERROR="USER_FORGET_PASSWORD_ERROR";


// Verify otp for forget password

export const USER_VERIFYOTP_REQUEST="USER_VERIFYOTP_REQUEST";
export const USER_VERIFYOTP_SUCCESS="USER_VERIFYOTP_SUCCESS";
export const USER_VERIFYOTP_ERROR="USER_VERIFYOTP_ERROR";

// Reset password for forget password


export const USER_RESET_PASSWORD_REQUEST="USER_RESET_PASSWORD_REQUEST";
export const USER_RESET_PASSWORD_SUCCESS="USER_RESET_PASSWORD_SUCCESS";
export const USER_RESET_PASSWORD_ERROR="USER_RESET_PASSWORD_ERROR";


