// final report in ms word
export const GET_FINAL_REPORT_REQUEST = "GET_FINAL_REPORT_REQUEST";
export const GET_FINAL_REPORT_SUCCESS = "GET_FINAL_REPORT_SUCCESS";
export const GET_FINAL_REPORT_ERROR = "GET_FINAL_REPORT_ERROR";

// final report in pdf

export const GET_FINAL_REPORT_PDF_REQUEST = "GET_FINAL_REPORT_PDF_REQUEST";
export const GET_FINAL_REPORT_PDF_SUCCESS = "GET_FINAL_REPORT_PDF_SUCCESS";
export const GET_FINAL_REPORT_PDF_ERROR = "GET_FINAL_REPORT_PDF_ERROR";


