// get admin-list
export const GET_ADMIN_DATA_REQUEST = "GET_ADMIN_DATA_REQUEST";
export const GET_ADMIN_DATA_SUCCESS = "GET_ADMIN_DATA_SUCCESS";
export const GET_ADMIN_DATA_ERROR = "GET_ADMIN_DATA_ERROR";
