//Manually send pdf to multiple whatsapp users
export const WHATSAPP_USERS_REPORT_PDF_REQUEST =
  "WHATSAPP_USERS_REPORT_PDF_REQUEST";
export const WHATSAPP_USERS_REPORT_PDF_SUCCESS =
  "WHATSAPP_USERS_REPORT_PDF_SUCCESS";
export const WHATSAPP_USERS_REPORT_PDF_ERROR =
  "WHATSAPP_USERS_REPORT_PDF_ERROR";

//Manually send pdf to multiple email users
export const EMAIL_USERS_REPORT_PDF_REQUEST = "EMAIL_USERS_REPORT_PDF_REQUEST";
export const EMAIL_USERS_REPORT_PDF_SUCCESS = "EMAIL_USERS_REPORT_PDF_SUCCESS";
export const EMAIL_USERS_REPORT_PDF_ERROR = "EMAIL_USERS_REPORT_PDF_ERROR";

//Manually send MSWord to multiple email users
export const EMAIL_USERS_REPORT_MSWord_REQUEST =
  "EMAIL_USERS_REPORT_MSWord_REQUEST";
export const EMAIL_USERS_REPORT_MSWord_SUCCESS =
  "EMAIL_USERS_REPORT_MSWord_SUCCESS";
export const EMAIL_USERS_REPORT_MSWord_ERROR =
  "EMAIL_USERS_REPORT_MSWord_ERROR";
