// get supervisor dashboard list
export const GET_AUDITOR_DATA_REQUEST = "GET_AUDITOR_DATA_REQUEST";
export const GET_AUDITOR_DATA_SUCCESS = "GET_AUDITOR_DATA_SUCCESS";
export const GET_AUDITOR_DATA_ERROR = "GET_AUDITOR_DATA_ERROR";



